name: Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"

  pull_request:
  workflow_dispatch:

jobs:
  images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [php]
